### ISSUE TITLE
[Enchancement] Remove this huge typography

### ISSUE THREAD

**Issue by DamsDev1** [Ipmake/PerPlexed#1]
Hello, great project! 

However, I find this big typo + icon unnecessary.
Plex libraries can only be movies or series. So when we're on a library, we already know what kind of videos we're going to browse. 
What's more, as for the episodes, the rest of the design already suggests that it's an episode, it's just redundancy.
![image](https://github.com/Ipmake/PerPlexed/assets/60252259/756e7d20-b19a-4f24-bb70-fc6edca434f4)

**Comment by Ipmake** [comment]
Font and Icon size slightly decreased to be less aggressive bca5bbc
