### ISSUE TITLE
[Bug] Playback preview shows a black box instead of the preview of that timestamp

### ISSUE THREAD

**Issue by lokwaniyash** [Ipmake/PerPlexed#22]
![image](https://github.com/user-attachments/assets/48e10d3b-6609-41c9-a9f3-c731e059425f)

Steps to reproduce
1. Play any media
2. Hover on the timeline to view the preview box

**Comment by lokwaniyash** [comment]
after some digging figured out that the url used to get the thumbnail images `library/parts/xxxx/indexes/sd/xxxxx` was giving 404, since my preview thumbnails were generated, hence `indexes/sd` was not available, found this as per these python plexapi docs

https://python-plexapi.readthedocs.io/en/latest/modules/media.html
![image](https://github.com/user-attachments/assets/c2b2e137-d66a-405e-b04a-4be247a19b86)

maybe there could be a conditional visibility that if the thumbnails are not available they shouldn't be shown

**Comment by Ipmake** [comment]
Hey, thanks for the suggestion. I just coded up a fix and will implement it with the next version.
