### ISSUE TITLE
[Feature] Changing the color of the Watched icon on a TV Show or Movie

### ISSUE THREAD

**Issue by lokwaniyash** [Ipmake/PerPlexed#23]
Suggesting changing the Watched icon color from green to something grayscale, to suit the UI of the whole site

![image](https://github.com/user-attachments/assets/ea94f948-0f7e-42d1-8558-f08b495d21c1)

**Comment by lokwaniyash** [comment]
To add to this, the watched icon doesn't appear on movies, please add that as well for future reference

**Comment by Ipmake** [comment]
Implemented with [v0.9.4](https://github.com/Ipmake/PerPlexed/releases/tag/v0.9.4)
