### ISSUE TITLE
No libraries shown

### ISSUE THREAD

**Issue by MaggiWuerze** [Ipmake/PerPlexed#5]
On a fresh install no libraries are shown and no way to choose from existing ones. Login worked but afterwards I only get an empty page with a WIP in the bottom left

![image](https://github.com/Ipmake/PerPlexed/assets/9729962/a6283700-09f9-47dc-8909-0aa8f966042f)

**Comment by Ipmake** [comment]
Check your browser console

**Comment by MaggiWuerze** [comment]
![](https://i.imgur.com/64U6OtD.png)

**Comment by MaggiWuerze** [comment]
it was the missing http:// at the beginning of the Plex address
